on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["zynq", "zynqmp"]

    name: build/${{ matrix.platform }}
    runs-on: ubuntu-latest

    steps:
      
      # Download artifact of image
      - uses: actions/download-artifact@v4
        with:
          name: pandablocks-dev-container
          path: .

      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-rootfs
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      # Run make inside the container 
      - name: Make zips
        run: |
          docker load --input pandablocks-dev-container.tar
          docker run \
            -v "${{ github.workspace }}:/repos" \
            -v "${{ github.workspace }}/build:/build" \
            pandablocks-dev-container:latest \
            /bin/bash -c \
            "cd PandABlocks-rootfs && ln -s CONFIG.example CONFIG && make zips PLATFORM=${{ matrix.platform }}"

      # Upload zips as artifact
      - name: Upload deps and boot build files
        uses: actions/upload-artifact@v4
        with:
          name: zips-${{ matrix.platform }}
          path: ./build/PandA-rootfs-${{ matrix.platform }}/*.zip
