on:
  workflow_call:

jobs:
  container-release:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    steps:

      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: PandABlocks-rootfs

      - name: Checkout rootfs builder
        uses: actions/checkout@v4
        with:
          repository: dls-controls/rootfs
          path: rootfs

      - name: Checkout annotypes
        uses: actions/checkout@v4
        with:
          repository: dls-controls/annotypes
          path: annotypes

      - name: Checkout pymalcolm
        uses: actions/checkout@v4
        with:
          repository: dls-controls/pymalcolm
          path: pymalcolm

      - name: Checkout malcolmjs
        uses: actions/checkout@v4
        with:
          repository: dls-controls/malcolmjs
          path: malcolmjs

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/pandablocks/pandablocks-dev-container
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Rebuild and release CI image
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: ./PandABlocks-rootfs/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          push: ${{ github.event_name != 'pull_request' }}
          target: developer

      - name: Docker meta
        id: cimeta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/pandablocks/pandablocks-ci-container
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest

      - name: Rebuild and release image
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: ./PandABlocks-rootfs/Dockerfile
          tags: ${{ steps.cimeta.outputs.tags }}
          labels: ${{ steps.cimeta.outputs.labels }}
          cache-from: type=gha
          push: ${{ github.event_name != 'pull_request' }}